name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    # You can define any steps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install packages
        run: |
            sudo apt update
            sudo apt install -y --no-install-recommends git cmake ninja-build gperf \
                ccache dfu-util device-tree-compiler wget \
                python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
                make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1
            cmake --version
            python3 --version
            dtc --version
      - name: Install West
        run: |
            pip3 install --user -U west pyelftools grpcio-tools
            echo 'export PATH=~/.local/bin:"$PATH"' >> ~/.bashrc
            source ~/.bashrc
      - name: Cache Zephyr SDK
        id: cache-zephyr
        uses: actions/cache@v4
        with:
            path: /home/runner/zephyr-sdk-0.16.3
            key: zephyr-sdk-0-16-3-arm-zephyr-eabi
      - name: Download Zephyr SDK
        if: ${{ steps.cache-zephyr.outputs.cache-hit != 'true' }}
        run: |
            cd ~
            wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.3/zephyr-sdk-0.16.3_linux-x86_64.tar.xz
            wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.3/sha256.sum | shasum --check --ignore-missing
            tar xvf zephyr-sdk-0.16.3_linux-x86_64.tar.xz
      - name: Install Zephyr SDK components
        run: |
            cd ~/zephyr-sdk-0.16.3
            ./setup.sh -h -c -t arm-zephyr-eabi
      - name: Cache west modules
        uses: actions/cache@v4
        continue-on-error: true
        env:
          cache_name: cache-west-modules
        with:
          path: dependencies/
          key: ${{ runner.os }}-build-${{ env.cache_name }}-${{hashFiles('west/**/west*.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache_name }}-
      - name: Setup ZMK environment
        run: |
            west init -l west --mf west-test-standalone.yml
            west update --narrow
            west zephyr-export
      - name: Verify setup
        run: |
            west zmk-build tests/zmk-config/config -m tests/zmk-config . -n
      - name: Setup Node.js for Web UI
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
        working-directory: web
      - name: Generate types from proto
        run: npm run generate
        working-directory: web
