name: Sync Changes in Template
on:
  # cronjob trigger
  # schedule:
  # - cron: "0 0 1 * *"
  # manual trigger
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: template-sync
        id: template_sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: cormoran/zmk-module-template-with-custom-studio-rpc
          upstream_branch: main # defaults to main
          # pr_labels: <label1>,<label2>[,...] # defaults to template_sync
  repo-sync-fallback:
    runs-on: ubuntu-latest
    needs: repo-sync
    if: failure()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: false
      - name: template-sync-with-pat
        # If the above step fails due to permission issues (e.g. changes in .github/workflow/*),
        # try again with a personal access token.
        # The token requires `repo` and `workflow` scopes.
        uses: AndreasAugustin/actions-template-sync@v2
        with:
            source_repo_path: cormoran/zmk-module-template-with-custom-studio-rpc
            upstream_branch: main # defaults to main
            target_gh_token: ${{ secrets.GH_TOKEN }}
            # pr_labels: <label1>,<label2>[,...] # defaults to template_sync