name: Test ZMK Module

on:
  push:
    branches: ["**"]
    paths-ignore:
      - "web/**"
      - ".github/workflows/web-ui.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache west modules
        uses: actions/cache@v4
        continue-on-error: true
        env:
          cache_name: cache-west-modules
        with:
          path: dependencies/
          key: ${{ runner.os }}-build-${{ env.cache_name }}-${{hashFiles('west/**/west*.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache_name }}-
      - name: Init
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          west init -l west --mf west-test-standalone.yml
          west update --narrow
          west zephyr-export
      - name: Test
        run: python3 -m unittest -v
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zmk-firmware
          path: |
            build/*/zephyr/zmk.uf2
